AppBundle\Entity\Usuario:
    type: entity
    table: usuarios
    id:
        id:
            id: true
            type: integer
            options:
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 250
            options:
                fixed: false
            nullable: false
        surname:
            type: string
            length: 250
            options:
                fixed: false
            nullable: true
        description:
            type: string
            length: 250
            options:
                fixed: false
            nullable: true
        email:
            type: string
            length: 250
            options:
                fixed: false
                default: email@cliente.es
            nullable: false
        password:
            type: string
            length: 250
            options:
                fixed: false
            nullable: true
        image:
            type: string
            length: 250
            options:
                fixed: false
            nullable: true
    lifecycleCallbacks: {  }
