AppBundle\Entity\Producto:
    type: entity
    table: productos
    id:
        id:
            id: true
            type: integer
            options:
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 250
            options:
                fixed: false
            nullable: true
        description:
            type: string
            length: 250
            options:
                fixed: false
                default: 'esta es la descripción por defecto . '
            nullable: true
        price:
            type: float
            precision: 10
            scale: 0
            options:
                default: '0'
            nullable: false
    lifecycleCallbacks: {  }
