lacueva\BlogBundle\Entity\Cases:
    type: entity
    table: null
    repositoryClass: lacueva\BlogBundle\Repository\CasesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idCase:
            type: string
            length: 255
            unique: true
            column: id_case
        url:
            type: string
            length: 255
        description:
            nullable: true
            type: string
            length: 255
        type:
            type: string
            length: 255
        requestedBy:
            type: string
            length: 255
        requesterDetails:
            nullable: true
            type: json_array
        createdAtDate:
            type: float
        createdAtSeconds:
            type: integer
        createdAtMilliseconds:
            type: integer
        proactiveChat:
            type: boolean
        pageUrl:
            type: string
            length: 255
        referrerUrl:
            nullable: true
            type: string
            length: 255
        entryUrl:
            nullable: true
            type: string
            length: 255
        ipAddress:
            type: string
            length: 255
        userAgent:
            type: string
            length: '512'
        browser:
            type: string
            length: 255
        os:
            type: string
            length: 255
        countryCode:
            nullable: true
            type: string
            length: '10'
        country:
            nullable: true
            type: string
            length: 255
        region:
            nullable: true
            type: string
            length: 255
        city:
            nullable: true
            type: string
            length: 255
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
        sourceId:
            nullable: true
            type: integer
        chatWaittime:
            type: integer
        chatDuration:
            type: integer
        surveyScore:
            type: integer
            nullable: true
        languageCode:
            nullable: true
            type: string
            length: 255
        transcripts:
            type: json_array
            nullable: true
             
        javascriptVariables:
            nullable: true
            type: json_array
    lifecycleCallbacks: {  }
