lacueva\BlogBundle\Entity\Productos:
    type: entity
    table: productos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
                default: 'esta es la descripción por defecto . '
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
    lifecycleCallbacks: {  }
