lacueva\BlogBundle\Entity\Transcript:
    type: entity
    table: null
    repositoryClass: lacueva\BlogBundle\Repository\TranscriptRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idTranscript:
            type: string
            length: 255
            column: id_transcript
        date:
            type: integer
        dateSeconds:
            type: integer
            column: date_seconds
        dateMiliseconds:
            type: integer
            column: date_miliseconds
        alias:
            type: string
            length: 255
        message:
            type: string
            length: '1000'
        idCase:
            type: string
            length: 255
            column: id_case
            
#        manyToOne:
#        idCategory:
#            targetEntity: Categories
#            cascade: {  }
#            fetch: LAZY
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                id_category:
#                    referencedColumnName: id
#            orphanRemoval: false
            
    lifecycleCallbacks: {  }
