AppBundle\Entity\Usuario:
    type: entity
    table: usuarios
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        surname:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
                default: email@cliente.es
        password:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
