<?php

namespace lacueva\BlogBundle\Repository;

/**
 * casesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class casesRepository extends \Doctrine\ORM\EntityRepository
{
}
