<?php

namespace lacueva\BlogBundle\Repository;

/**
 * CasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasesRepository extends \Doctrine\ORM\EntityRepository
{
	//TODO: IMPLEMENTAR AQUI LOS FINDBY 
}
