<?php

namespace lacueva\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EntriesRepo.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntriesRepo extends EntityRepository
{


    public function findAllOrdenadosPorIdUser()
    {
        return $this->getEntityManager()->createQuery(
                'SELECT e FROM BlogBundle:Entries e ORDER BY e.idUser'
                )->getResult();
    }
	
	public function getPaginateEntries($pagesize = 5 , $currentPage = 1)
	{
		$em =$this->getEntityManager();
		
		$dql = "SELECT e FROM  lacueva\BlogBundle\Entity\Entries e ORDER BY e.id DESC"; 
		
		$query = $em->createQuery($dql)
				->setFirstResult($pagesize * ($currentPage - 1))
				->setMaxResults($pagesize);
		
		
		$paginator = new \Doctrine\ORM\Tools\Pagination\Paginator($query, $fetchJoinCollection = true);
		
		return $paginator;

		
	}
	
	
}
