<?php

namespace lacueva\BlogBundle\Entity;

/**
 * EntriesRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntriesRepo extends \Doctrine\ORM\EntityRepository
{

	function findAllOrdenadosPorIdUser()
	{
		return $this->getEntityManager()->createQuery(
				'SELECT e FROM BlogBundle:Entries e ORDER BY e.idUser'
				)->getResult();
	}
	
	
}

